export enum EOnboardingStep {
  initialization = 'onboardingStepInitialization',
  welcomeIndividual = 'onboardingStepWelcomeIndividual',
  infoIndividual = 'onboardingStepPersonIndividual',
  pollingIndividual = 'onboardingStepPollingIndividual',
  docsIndividual = 'onboardingStepDocsIndividual',
  feeIndividual = 'onboardingStepFeeIndividual',
  congratulationsIndividual = 'onboardingStepCongratulationsIndividual',
  welcomeCorporate = 'onboardingStepWelcomeCorporate',
  docsInfoCorporate = 'onboardingStepDocsInfoCorporate',
  docsRepresentativeCorporate = 'onboardingStepDocsRepresentativeCorporate',
  docsMembersCorporate = 'onboardingStepDocsMembersCorporate',
  docsOwnersCorporate = 'onboardingStepDocsOwnersCorporate',
  infoCorporate = 'onboardingStepCompanyCorporate',
  pollingCorporate = 'onboardingStepPollingCorporate',
  congratulationsCorporate = 'onboardingStepCongratulationsCorporate',
}
